stages:
  - build
  - deploy

build:
  stage: build
  image: python:3.8-alpine
  script:
    - pip install -r requirements.txt
    - lektor build --output-path public
  artifacts:
    paths:
      - public/
    expire_in: 1h

deploy:
  stage: deploy
  image: alpine:3.9

  variables:
    SSH_HOST: vhost.wirtel.be
    SSH_USER: root
    SSH_PATH: /home/www/www.python-fosdem.org/src/

  script:
    - apk add rsync openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -hrvz --chown=www-data:www-data --delete --exclude=_ -e 'ssh -i id_rsa' public/ ${SSH_USER}@${SSH_HOST}:${SSH_PATH}
  only:
    - master
