image: python:3.7

before_script:
  - apt-get update
  - 'which ssh-agent || ( apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - apt-get install --yes --force-yes rsync
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

pages:
  script:
    - pip install lektor
    - lektor build --output-path public
    - rsync -hrvz --delete --exclude=_ -e 'ssh -i id_rsa' public/ root@vhost.wirtel.be:/home/www/www.python-fosdem.org/src/
  artifacts:
    paths:
      - public
  only:
    - master
  
