# https://taskfile.dev

version: '3'

tasks:
  serve:
    desc: Serve the site
    cmds:
      - .venv/bin/lektor serve --verbose --prune

  build:
    desc: Build the site
    cmds:
      - .venv/bin/lektor build --verbose --prune

  clean:
    desc: Clean the artifcats of the site
    cmds:
      - .venv/bin/lektor clean --yes

  dependencies:install:
    desc: Install the dependencies
    cmds:
      - .venv/bin/python -m pip install -r requirements.txt pip-tools

  dependencies:build:
    desc: Build the dependencies via pip-tools
    cmds:
      - .venv/bin/pip-compile requirements.in --output-file requirements.txt

  dependencies:update:
    desc: Update the dependencies via pip-tools
    cmds:
      - .venv/bin/pip-compile --upgrade requirements.in --output-file requirements.txt